import React, { useState, useEffect, useRef } from "react";
import {
  ChevronDown,
  Download,
  FileText,
  User,
  Mail,
  Building,
  Briefcase,
  Phone,
  Globe,
  MapPin,
  UserCircle2,
} from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import pro from "../assets/profile.png";
import resume from "../assets/resume.png";
import letter from "../assets/letter.png";
import interview from "../assets/interview.png";
import job from "../assets/job.png";
import quiz from "../assets/quiz.png";

const cardVariants = {
  hidden: { opacity: 0, y: 40 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.7 } },
};

const RiseOnCoverLetter = () => {
  const navigate = useNavigate();

  // Sender details
  const [senderName, setSenderName] = useState("");
  const [senderEmail, setSenderEmail] = useState("");
  const [senderPhone, setSenderPhone] = useState("");
  const [senderWebsite, setSenderWebsite] = useState("");

  // Job and company
  const [profile, setProfile] = useState(""); // your core profile (e.g., MERN Developer)
  const [targetRole, setTargetRole] = useState(""); // role you're applying for
  const [company, setCompany] = useState("");

  // Recipient block (left column, like sample image)
  const [recipientName, setRecipientName] = useState("");
  const [recipientTitle, setRecipientTitle] = useState("Hiring Manager");
  const [recipientAddress, setRecipientAddress] = useState(""); // street, area
  const [recipientCityZip, setRecipientCityZip] = useState(""); // City, State ZIP

  // Letter content
  const [jobDescription, setJobDescription] = useState("");
  const [touched, setTouched] = useState({});
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedAt, setGeneratedAt] = useState("");
  const [paragraphs, setParagraphs] = useState([]); // structured body paragraphs

  // DOM ref for styled PDF export (html2pdf)
  const coverRef = useRef(null);

  const isInvalid = (field) => !field && touched[field];

  useEffect(() => {
    const userEmail = localStorage.getItem("userEmail");
    if (userEmail) setSenderEmail(userEmail);
  }, []);

  // Auto fill JD if all primary fields are present but JD is empty
  useEffect(() => {
    if (senderName && senderEmail && profile && targetRole && company && !jobDescription) {
      const autoGenerated = `We are seeking a skilled ${targetRole} at ${company}. The ideal candidate should have expertise in ${profile}, strong analytical skills, and a commitment to continuous improvement.`;
      setJobDescription(autoGenerated);
    }
  }, [senderName, senderEmail, profile, targetRole, company, jobDescription]);

  const handleSubmit = async () => {
    setTouched({
      senderName: true,
      senderEmail: true,
      profile: true,
      targetRole: true,
      company: true,
    });

    if (senderName && senderEmail && profile && targetRole && company) {
      setIsGenerating(true);
      await new Promise((resolve) => setTimeout(resolve, 800));

      const now = new Date();
      const formattedDate = now.toLocaleDateString("en-IN", {
        day: "numeric",
        month: "long",
        year: "numeric",
      });
      const formattedTime = now.toLocaleTimeString("en-IN", {
        hour: "2-digit",
        minute: "2-digit",
      });
      setGeneratedAt(`${formattedDate}, ${formattedTime}`);

      // Build body paragraphs to match the reference layout tone
      const p1 = `I am writing to express my interest in the ${targetRole} position at ${company}. With a strong background in ${profile}, I am confident in my ability to contribute effectively to your team.`;
      const p2 =
        jobDescription?.trim()
          ? jobDescription.trim()
          : `In my previous roles, I have demonstrated a commitment to delivering high-quality outcomes and cross-functional collaboration. I am skilled in problem solving, rapid learning, and applying best practices to ship reliable, maintainable solutions.`;
      const p3 = `Enclosed is my resume, which provides a detailed overview of my qualifications and experiences. I am confident that my skills align well with the requirements of the ${targetRole} role at ${company}.`;
      const p4 = `Thank you for considering my application. I would welcome the opportunity to discuss how my skills and experiences make me a strong fit for ${company}.`;

      setParagraphs([p1, p2, p3, p4]);
      setIsGenerating(false);
    }
  };

 // ...existing imports unchanged...

// inside the component, replace your handleDownloadPDF with this:
const handleDownloadPDF = async () => {
  if (!coverRef.current) return;

  try {
    // Use the bundle build (includes html2canvas + jsPDF)
    const mod = await import("html2pdf.js/dist/html2pdf.bundle.min.js");
    const html2pdf = mod.default || mod;

    const opt = {
      margin: [18, 18, 18, 18],
      filename: `${senderName || "Cover_Letter"}.pdf`,
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true, logging: false, scrollY: 0 },
      jsPDF: { unit: "pt", format: "a4", orientation: "portrait" },
      pagebreak: { mode: ["css", "legacy"] },
    };

    await html2pdf().set(opt).from(coverRef.current).save();
  } catch (err) {
    console.error("html2pdf error, falling back to jsPDF text export:", err);
    try {
      // Fallback: simple text export so user still gets a file
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "pt", format: "a4" });
      const margin = 40;
      const pageWidth = doc.internal.pageSize.getWidth();
      const maxWidth = pageWidth - margin * 2;

      const header = [
        (targetRole || "Target Role").toUpperCase(),
        (senderName || "Your Name").toUpperCase(),
        [senderPhone ? `T: ${senderPhone}` : null, senderWebsite ? `W: ${senderWebsite}` : null, senderEmail ? `E: ${senderEmail}` : null]
          .filter(Boolean)
          .join("  //  "),
        "",
      ].join("\n");

      const leftBlock = [
        recipientName || "",
        recipientTitle || "",
        company || "",
        recipientAddress || "",
        recipientCityZip || "",
        "",
      ]
        .filter(Boolean)
        .join("\n");

      const body = [
        `DEAR ${(recipientName || "Hiring Manager").toUpperCase()},`,
        "",
        ...paragraphs,
        "",
        "Thank you,",
        senderName || "Your Name",
        [senderEmail, senderPhone].filter(Boolean).join(" · "),
        "Enclosure",
      ].join("\n");

      // Write header
      doc.setFont("times", "bold");
      doc.setFontSize(12);
      doc.text(doc.splitTextToSize(header, maxWidth), margin, margin);

      // Left column block
      let y = margin + 80;
      doc.setFont("times", "normal");
      doc.setFontSize(11);
      const leftLines = doc.splitTextToSize(leftBlock, 180);
      doc.text(leftLines, margin, y);

      // Right column body
      const rightX = margin + 200;
      const bodyLines = doc.splitTextToSize(body, pageWidth - rightX - margin);
      doc.text(bodyLines, rightX, y);

      doc.save(`${senderName || "Cover_Letter"}_fallback.pdf`);
    } catch (fallbackErr) {
      console.error("Fallback jsPDF also failed:", fallbackErr);
      alert("Sorry, PDF download failed. Please try again or check the console for details.");
    }
  }
};

  return (
    <div className="flex min-h-screen bg-gradient-to-br from-orange-50 via-pink-50 to-blue-50 pt-20">
      {/* Sidebar */}
      <aside className="fixed left-0 top-20 w-28 md:w-32 lg:w-40 h-[calc(100vh-5rem)] bg-gradient-to-b from-gray-900 to-gray-700 shadow-xl text-white p-4 md:p-6 border-r border-gray-600 flex flex-col items-center z-40">
        <nav className="flex-1 space-y-6 text-center mt-2">
          <SidebarLink to="/myaccount" img={pro} label="Account" />
          <SidebarLink to="/dashboard" img={resume} label="Dashboard" />
          <SidebarLink to="/riseon-coverletter" img={letter} label="Letter" active />
          <SidebarLink to="/riseon-interview" img={interview} label="Interview" />
          <SidebarLink to="/riseon-job-boards" img={job} label="Jobs" />
          <SidebarLink to="/riseon-quiz" img={quiz} label="Quiz" />
        </nav>
      </aside>

      {/* Main Content */}
      <motion.main
        className="flex-1 p-6 md:p-8 ml-28 md:ml-32 lg:ml-40"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.8 }}
      >
        {/* Header */}
        <div className="text-center mb-12">
          <h2 className="text-4xl md:text-5xl font-extrabold bg-gradient-to-r from-orange-600 via-pink-600 to-blue-600 text-transparent bg-clip-text">
            Cover Letter Generator
          </h2>
          <p className="text-lg md:text-xl text-gray-700 mt-2">
            Create a modern, ATS-friendly cover letter in the format shown
          </p>
          <div className="h-1 w-32 bg-gradient-to-r from-orange-500 to-yellow-400 mx-auto mt-3 rounded-full"></div>
        </div>

        {/* Card */}
        <motion.div
          className="max-w-7xl mx-auto bg-white shadow-2xl rounded-3xl overflow-hidden"
          variants={cardVariants}
          initial="hidden"
          animate="visible"
        >
          {/* Header */}
          <div className="bg-gradient-to-r from-orange-500 to-pink-500 p-8 text-white">
            <h1 className="text-3xl md:text-4xl font-bold">Generate Letter</h1>
            <p className="text-lg opacity-90">Styled like the uploaded sample</p>
          </div>

          {/* Body */}
          <div className="p-8 grid grid-cols-1 lg:grid-cols-2 gap-12">
            {/* Form */}
            <FormSection
              senderName={senderName}
              senderEmail={senderEmail}
              senderPhone={senderPhone}
              senderWebsite={senderWebsite}
              profile={profile}
              targetRole={targetRole}
              company={company}
              recipientName={recipientName}
              recipientTitle={recipientTitle}
              recipientAddress={recipientAddress}
              recipientCityZip={recipientCityZip}
              jobDescription={jobDescription}
              setSenderName={setSenderName}
              setSenderEmail={setSenderEmail}
              setSenderPhone={setSenderPhone}
              setSenderWebsite={setSenderWebsite}
              setProfile={setProfile}
              setTargetRole={setTargetRole}
              setCompany={setCompany}
              setRecipientName={setRecipientName}
              setRecipientTitle={setRecipientTitle}
              setRecipientAddress={setRecipientAddress}
              setRecipientCityZip={setRecipientCityZip}
              setJobDescription={setJobDescription}
              touched={touched}
              setTouched={setTouched}
              isGenerating={isGenerating}
              handleSubmit={handleSubmit}
            />

            {/* Preview (Styled like the reference) */}
            <motion.div
              className="bg-gray-50 rounded-2xl p-0 border border-gray-200"
              variants={cardVariants}
              initial="hidden"
              animate="visible"
              transition={{ delay: 0.4 }}
            >
              <div className="flex items-center justify-between px-6 pt-4">
                <h2 className="text-2xl font-bold text-gray-800">Preview</h2>
                {paragraphs.length > 0 && (
                  <button
                    onClick={handleDownloadPDF}
                    className="mb-2 flex items-center gap-2 px-4 py-2 bg-blue-600 text-white text-sm rounded-xl shadow-md hover:bg-blue-700 transition-all"
                  >
                    <Download size={16} />
                    Download PDF
                  </button>
                )}
              </div>

              {paragraphs.length > 0 ? (
                <div className="bg-white">
                  {/* The A4-like canvas to export */}
                  <div
                    ref={coverRef}
                    className="mx-auto my-6 w-full max-w-[900px] bg-white text-gray-900"
                  >
                    <div className="px-10 pt-10">
                      {/* Role smallcaps */}
                      <div className="tracking-widest text-gray-500 font-semibold"
                           style={{ fontVariant: "small-caps", letterSpacing: "0.15em" }}>
                        {targetRole ? targetRole : "Target Role"}
                      </div>

                      {/* Big Name */}
                      <div className="mt-1 text-4xl sm:text-5xl font-extrabold">
                        {(senderName || "Your Name").toUpperCase()}
                      </div>

                      {/* Contact line */}
                      <div className="mt-3 text-sm text-gray-600">
                        {senderPhone && <>Phone: {senderPhone}{"  "}<span className="opacity-60">|</span>{"  "}</>}
                        {senderWebsite && <>Website: {senderWebsite}{"  "}<span className="opacity-60">|</span>{"  "}</>}
                        {senderEmail && <>Email: {senderEmail}</>}
                      </div>
                    </div>

                    <div className="mt-8 grid grid-cols-1 sm:grid-cols-3 gap-8 px-10 pb-12">
                      {/* Left column - Recipient block */}
                      <div className="sm:col-span-1 text-sm text-gray-700">
                        {(recipientName || recipientTitle || company) && (
                          <div className="space-y-1">
                            {recipientName && <div className="font-medium">{recipientName}</div>}
                            {recipientTitle && <div>{recipientTitle}</div>}
                            {company && <div>{company}</div>}
                            {recipientAddress && <div>{recipientAddress}</div>}
                            {recipientCityZip && <div>{recipientCityZip}</div>}
                          </div>
                        )}
                      </div>

                      {/* Right column - Letter body */}
                      <div className="sm:col-span-2">
                        {/* Greeting */}
                        <div className="font-extrabold tracking-wide">
                          DEAR {recipientName ? recipientName.toUpperCase() : "HIRING MANAGER"},
                        </div>
                        <div className="border-t mt-2 mb-4"></div>

                        {/* Body paragraphs */}
                        <div className="space-y-4 text-[15px] leading-[1.8] text-gray-800 font-serif">
                          {paragraphs.map((p, i) => (
                            <p key={i}>{p}</p>
                          ))}
                        </div>

                        {/* Closing */}
                        <div className="mt-6 space-y-1 text-gray-800">
                          <div>Thank you,</div>
                          <div className="font-medium">{senderName || "Your Name"}</div>
                          <div className="text-sm text-gray-600">
                            {senderEmail || ""}{senderEmail && senderPhone ? " · " : ""}{senderPhone || ""}
                          </div>
                          <div className="text-sm text-gray-500">Enclosure</div>
                          {generatedAt && (
                            <div className="text-xs text-gray-400 mt-2">Generated on: {generatedAt}</div>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="bg-white rounded-xl shadow-lg p-12 border border-gray-200 text-center text-gray-400 m-6">
                  <FileText size={48} className="mx-auto mb-4 opacity-50" />
                  <p className="text-lg font-medium">Your cover letter will appear here</p>
                  <p className="text-sm mt-2">Fill out the form and click “Generate Cover Letter”</p>
                </div>
              )}
            </motion.div>
          </div>
        </motion.div>
      </motion.main>
    </div>
  );
};

/* ------------- Helper Components ------------- */

const SidebarLink = ({ to, img, label, active }) => (
  <Link
    to={to}
    className={`flex flex-col items-center transition-all duration-300 ${
      active ? "text-yellow-300 scale-110" : "text-white/80 hover:text-yellow-300 hover:scale-105"
    }`}
  >
    <img src={img} alt={label} className="w-10 h-10 rounded-full mb-1" />
    <span className="text-xs">{label}</span>
  </Link>
);

const FormSection = ({
  senderName,
  senderEmail,
  senderPhone,
  senderWebsite,
  profile,
  targetRole,
  company,
  recipientName,
  recipientTitle,
  recipientAddress,
  recipientCityZip,
  jobDescription,
  setSenderName,
  setSenderEmail,
  setSenderPhone,
  setSenderWebsite,
  setProfile,
  setTargetRole,
  setCompany,
  setRecipientName,
  setRecipientTitle,
  setRecipientAddress,
  setRecipientCityZip,
  setJobDescription,
  touched,
  setTouched,
  isGenerating,
  handleSubmit,
}) => (
  <motion.div
    className="space-y-6"
    variants={cardVariants}
    initial="hidden"
    animate="visible"
    transition={{ delay: 0.2 }}
  >
    <h2 className="text-2xl font-bold text-gray-800 mb-2">Details</h2>

    {/* Sender */}
    <EnhancedInputField
      label="Your Full Name"
      icon={<User size={20} />}
      required
      value={senderName}
      setValue={setSenderName}
      touched={touched}
      setTouched={setTouched}
      fieldName="senderName"
      placeholder="e.g. Kai Carter"
    />

    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <EnhancedInputField
        label="Your Email"
        icon={<Mail size={20} />}
        required
        value={senderEmail}
        setValue={setSenderEmail}
        touched={touched}
        setTouched={setTouched}
        fieldName="senderEmail"
        type="email"
        placeholder="e.g. kai@example.com"
      />
      <EnhancedInputField
        label="Your Phone (optional)"
        icon={<Phone size={20} />}
        value={senderPhone}
        setValue={setSenderPhone}
        touched={touched}
        setTouched={setTouched}
        fieldName="senderPhone"
        placeholder="e.g. 678-555-0103"
      />
    </div>

    <EnhancedInputField
      label="Your Website (optional)"
      icon={<Globe size={20} />}
      value={senderWebsite}
      setValue={setSenderWebsite}
      touched={touched}
      setTouched={setTouched}
      fieldName="senderWebsite"
      placeholder="e.g. www.example.com"
    />

    {/* Role and company */}
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <EnhancedInputField
        label="Target Job Role"
        icon={<Briefcase size={20} />}
        required
        value={targetRole}
        setValue={setTargetRole}
        touched={touched}
        setTouched={setTouched}
        fieldName="targetRole"
        placeholder="e.g. General Practitioner / Frontend Developer"
      />
      <EnhancedInputField
        label="Company Name"
        icon={<Building size={20} />}
        required
        value={company}
        setValue={setCompany}
        touched={touched}
        setTouched={setTouched}
        fieldName="company"
        placeholder="e.g. Sydney Mattos MD"
      />
    </div>

    {/* Profile select */}
    <div>
      <label className="block text-sm font-semibold mb-2 text-gray-700">
        Your Profile <span className="text-red-500">*</span>
      </label>
      <select
        value={profile}
        onChange={(e) => setProfile(e.target.value)}
        onBlur={() => setTouched((prev) => ({ ...prev, profile: true }))}
        className="w-full border-2 border-gray-300 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-orange-500 focus:border-orange-500"
      >
        <option value="">-- Select Profile --</option>
        <option>MERN Stack Developer</option>
        <option>Frontend Developer</option>
        <option>Backend Developer</option>
        <option>Data Scientist</option>
        <option>UI/UX Designer</option>
        <option>Product Manager</option>
        <option>General Practitioner</option>
      </select>
      {!profile && touched.profile && (
        <p className="text-red-500 text-sm mt-1">Please select your profile.</p>
      )}
    </div>

    {/* Recipient block */}
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <EnhancedInputField
        label="Recipient Name (optional)"
        icon={<UserCircle2 size={20} />}
        value={recipientName}
        setValue={setRecipientName}
        touched={touched}
        setTouched={setTouched}
        fieldName="recipientName"
        placeholder="e.g. Jozi Kos"
      />
      <EnhancedInputField
        label="Recipient Title (optional)"
        icon={<Briefcase size={20} />}
        value={recipientTitle}
        setValue={setRecipientTitle}
        touched={touched}
        setTouched={setTouched}
        fieldName="recipientTitle"
        placeholder="e.g. Hiring Manager"
      />
    </div>

    <EnhancedInputField
      label="Recipient Address (optional)"
      icon={<MapPin size={20} />}
      value={recipientAddress}
      setValue={setRecipientAddress}
      touched={touched}
      setTouched={setTouched}
      fieldName="recipientAddress"
      placeholder="e.g. 210 Stars Avenue"
    />
    <EnhancedInputField
      label="City, State ZIP (optional)"
      icon={<MapPin size={20} />}
      value={recipientCityZip}
      setValue={setRecipientCityZip}
      touched={touched}
      setTouched={setTouched}
      fieldName="recipientCityZip"
      placeholder="e.g. Berkeley, CA 45678"
    />

    {/* JD */}
    <div>
      <label className="block text-sm font-semibold mb-2 text-gray-700">
        Job Description (Optional)
      </label>
      <textarea
        value={jobDescription}
        onChange={(e) => setJobDescription(e.target.value)}
        rows={4}
        className="w-full border-2 border-gray-300 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-orange-500 focus:border-orange-500 resize-none"
        placeholder="Paste the job description or leave blank..."
      />
    </div>

    <button
      onClick={handleSubmit}
      disabled={isGenerating}
      className="w-full bg-gradient-to-r from-orange-500 to-pink-500 text-white py-4 rounded-xl font-bold text-lg shadow-md hover:shadow-lg hover:scale-105 transition-all flex items-center justify-center gap-3"
    >
      {isGenerating ? (
        <>
          <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
          Generating...
        </>
      ) : (
        <>Generate Cover Letter</>
      )}
    </button>
  </motion.div>
);

const EnhancedInputField = ({
  label,
  icon,
  value,
  setValue,
  touched,
  setTouched,
  fieldName,
  placeholder,
  required = false,
  type = "text",
}) => {
  const isInvalid = required && !value && touched[fieldName];
  return (
    <div>
      <label className="block text-sm font-semibold mb-2 text-gray-700">
        {label} {required && <span className="text-red-500">*</span>}
      </label>
      <div className="relative">
        <div className="absolute inset-y-0 left-0 pl-3 flex items-center text-gray-400">{icon}</div>
        <input
          type={type}
          value={value}
          onChange={(e) => setValue(e.target.value)}
          onBlur={() => setTouched((prev) => ({ ...prev, [fieldName]: true }))}
          placeholder={placeholder}
          className={`w-full border-2 rounded-xl pl-12 pr-4 py-3 text-sm focus:ring-2 focus:ring-orange-500 focus:border-orange-500 ${
            isInvalid ? "border-red-500" : "border-gray-300"
          }`}
        />
      </div>
      {isInvalid && <p className="text-red-500 text-sm mt-1">Please enter {label}.</p>}
    </div>
  );
};

export default RiseOnCoverLetter;